-- Normalize users.language values to canonical Language enum strings
-- Canonical values follow crate::models::Language::as_db_str()

-- Ensure the column can store canonical values like "portuguese", "indonesian", etc.
ALTER TABLE users
ALTER COLUMN language TYPE VARCHAR(32);

UPDATE users
SET language = CASE LOWER(TRIM(language))
    -- Legacy numeric IDs
    WHEN '0' THEN 'unknown'
    WHEN '1' THEN 'french'
    WHEN '2' THEN 'english'
    WHEN '3' THEN 'german'
    WHEN '4' THEN 'japanese'
    WHEN '5' THEN 'spanish'
    WHEN '6' THEN 'portuguese'
    -- Legacy ISO-like codes
    WHEN 'fre' THEN 'french'
    WHEN 'fra' THEN 'french'
    WHEN 'eng' THEN 'english'
    WHEN 'ger' THEN 'german'
    WHEN 'deu' THEN 'german'
    WHEN 'jpn' THEN 'japanese'
    WHEN 'spa' THEN 'spanish'
    WHEN 'por' THEN 'portuguese'
    -- Legacy prefixed values
    WHEN 'langunknown' THEN 'unknown'
    WHEN 'langfr' THEN 'french'
    WHEN 'langen' THEN 'english'
    WHEN 'langde' THEN 'german'
    WHEN 'langjp' THEN 'japanese'
    WHEN 'langes' THEN 'spanish'
    WHEN 'langpo' THEN 'portuguese'
    -- ISO-639-1 shortcuts sometimes used by clients
    WHEN 'fr' THEN 'french'
    WHEN 'en' THEN 'english'
    WHEN 'de' THEN 'german'
    WHEN 'es' THEN 'spanish'
    WHEN 'pt' THEN 'portuguese'
    WHEN 'it' THEN 'italian'
    WHEN 'zh' THEN 'chinese'
    WHEN 'ru' THEN 'russian'
    WHEN 'ar' THEN 'arabic'
    WHEN 'nl' THEN 'dutch'
    WHEN 'sv' THEN 'swedish'
    WHEN 'no' THEN 'norwegian'
    WHEN 'da' THEN 'danish'
    WHEN 'fi' THEN 'finnish'
    WHEN 'pl' THEN 'polish'
    WHEN 'cs' THEN 'czech'
    WHEN 'hu' THEN 'hungarian'
    WHEN 'ro' THEN 'romanian'
    WHEN 'tr' THEN 'turkish'
    WHEN 'ko' THEN 'korean'
    WHEN 'la' THEN 'latin'
    WHEN 'el' THEN 'greek'
    WHEN 'hr' THEN 'croatian'
    WHEN 'hi' THEN 'hindi'
    WHEN 'he' THEN 'hebrew'
    WHEN 'fa' THEN 'persian'
    WHEN 'ca' THEN 'catalan'
    WHEN 'th' THEN 'thai'
    WHEN 'vi' THEN 'vietnamese'
    WHEN 'id' THEN 'indonesian'
    WHEN 'ms' THEN 'malay'
    -- Already canonical (kept as-is)
    WHEN 'unknown' THEN 'unknown'
    WHEN 'french' THEN 'french'
    WHEN 'english' THEN 'english'
    WHEN 'german' THEN 'german'
    WHEN 'spanish' THEN 'spanish'
    WHEN 'italian' THEN 'italian'
    WHEN 'portuguese' THEN 'portuguese'
    WHEN 'japanese' THEN 'japanese'
    WHEN 'chinese' THEN 'chinese'
    WHEN 'russian' THEN 'russian'
    WHEN 'arabic' THEN 'arabic'
    WHEN 'dutch' THEN 'dutch'
    WHEN 'swedish' THEN 'swedish'
    WHEN 'norwegian' THEN 'norwegian'
    WHEN 'danish' THEN 'danish'
    WHEN 'finnish' THEN 'finnish'
    WHEN 'polish' THEN 'polish'
    WHEN 'czech' THEN 'czech'
    WHEN 'hungarian' THEN 'hungarian'
    WHEN 'romanian' THEN 'romanian'
    WHEN 'turkish' THEN 'turkish'
    WHEN 'korean' THEN 'korean'
    WHEN 'latin' THEN 'latin'
    WHEN 'greek' THEN 'greek'
    WHEN 'croatian' THEN 'croatian'
    WHEN 'hindi' THEN 'hindi'
    WHEN 'hebrew' THEN 'hebrew'
    WHEN 'persian' THEN 'persian'
    WHEN 'catalan' THEN 'catalan'
    WHEN 'thai' THEN 'thai'
    WHEN 'vietnamese' THEN 'vietnamese'
    WHEN 'indonesian' THEN 'indonesian'
    WHEN 'malay' THEN 'malay'
    ELSE 'unknown'
END
WHERE language IS NOT NULL;
