//! Authentication endpoints

use axum::{extract::State, Json};
use chrono::NaiveDate;
use serde::{Deserialize, Serialize};
use serde_with::{serde_as, DisplayFromStr};
use utoipa::ToSchema;

use crate::error::AppResult;
#[allow(unused_imports)] // Used in utoipa macros
use crate::error::ErrorResponse;
use crate::models::Language;
use crate::services::audit;

use super::ClientIp;

use super::{AuthenticatedUser, PasswordChangeUser};


/// Build the auth routes for this domain.
pub fn router() -> axum::Router<crate::AppState> {
    use axum::routing::{get, post, put};
    axum::Router::new()
        .route("/auth/login", post(login))
        .route("/auth/me", get(me))
        .route("/auth/profile", put(super::users::update_my_profile))
        .route("/auth/verify-2fa", post(verify_2fa))
        .route("/auth/verify-recovery", post(verify_recovery))
        .route("/auth/request-password-reset", post(request_password_reset))
        .route("/auth/reset-password", post(reset_password))
        .route("/auth/change-password", post(change_password))
        .route("/auth/setup-2fa", post(setup_2fa))
        .route("/auth/disable-2fa", post(disable_2fa))
}

#[derive(Serialize)]
struct LoginIdentifierAudit<'a> {
    login: &'a str,
}

#[derive(Clone, Copy, Serialize)]
struct TwoFaVerifyAttemptAudit {
    trust_device: bool,
    has_device_id: bool,
}

#[derive(Serialize)]
struct PasswordChangedViaResetAudit {
    source: &'static str,
}

#[derive(Serialize)]
struct UserIdAudit {
    user_id: i64,
}

/// Login request body
#[derive(Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct LoginRequest {
    /// Username or login
    pub username: String,
    /// Password
    pub password: String,
    /// Device ID (optional, for bypassing 2FA if device is already trusted)
    pub device_id: Option<String>,
}

/// Login response with JWT token
#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct LoginResponse {
    /// JWT access token (None if 2FA is required)
    pub token: Option<String>,
    /// Token type (always "Bearer")
    pub token_type: String,
    /// Token expiration time in seconds
    pub expires_in: i64,
    /// User information
    pub user: UserInfo,
    /// Whether 2FA verification is required
    pub requires_2fa: bool,
    /// 2FA method if required ("totp" or "email")
    pub two_factor_method: Option<String>,
    /// Device ID generated by server (only present if 2FA is required, client should store and reuse it)
    pub device_id: Option<String>,
    /// When true the user must change their password before continuing
    pub must_change_password: bool,
}

/// User information returned after login
#[serde_as]
#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct UserInfo {
    /// User ID
    #[serde_as(as = "DisplayFromStr")]
    #[schema(value_type = String)]
    pub id: i64,
    /// Login/username (primary identifier, required)
    pub login: String,
    /// Email (optional)
    pub email: Option<String>,
    /// First name
    pub firstname: Option<String>,
    /// Last name
    pub lastname: Option<String>,
    /// Street address
    pub addr_street: Option<String>,
    /// Zip code
    pub addr_zip_code: Option<i32>,
    /// City
    pub addr_city: Option<String>,
    /// Phone number
    pub phone: Option<String>,
    /// Birth date (ISO `YYYY-MM-DD`)
    pub birthdate: Option<NaiveDate>,
    /// Account type name
    pub account_type: String,
    /// Preferred language
    pub language: Language,
}



/// Login endpoint - authenticate and get JWT token
#[utoipa::path(
    post,
    path = "/auth/login",
    tag = "auth",
    request_body = LoginRequest,
    responses(
        (status = 200, description = "Login successful", body = LoginResponse),
        (status = 401, description = "Invalid credentials", body = ErrorResponse)
    )
)]
pub async fn login(
    State(state): State<crate::AppState>,
    ClientIp(ip): ClientIp,
    Json(request): Json<LoginRequest>,
) -> AppResult<Json<LoginResponse>> {
    let login_result = state
        .services
        .users
        .authenticate(&request.username, &request.password, request.device_id.as_deref())
        .await;

    match &login_result {
        Ok((_, user)) => {
            state.services.audit.log(
                audit::event::AUTH_LOGIN_SUCCESS,
                Some(user.id),
                Some("user"),
                Some(user.id),
                ip.clone(),
                Some(LoginIdentifierAudit {
                    login: request.username.as_str(),
                }),
            );
        }
        Err(_) => {
            state.services.audit.log(
                audit::event::AUTH_LOGIN_FAILED,
                None,
                None,
                None,
                ip.clone(),
                Some(LoginIdentifierAudit {
                    login: request.username.as_str(),
                }),
            );
        }
    }

    let (token, user) = login_result?;



    
    let requires_2fa = token.is_none() && user.two_factor_enabled.unwrap_or(false);
    let two_factor_method = if requires_2fa {
        user.two_factor_method.clone()
    } else {
        None
    };

    // Generate device_id if 2FA is required (client will store and reuse it)
    // reuse request.device_id if provided or generate a new one if not provided
    let device_id = request.device_id.clone().or_else(|| {
        if requires_2fa {
            use uuid::Uuid;
            Some(Uuid::new_v4().to_string())
        } else {
            None
        }
    });

    // If 2FA is enabled and method is email, send code
    if requires_2fa && two_factor_method.as_deref() == Some("email") {
        if let Some(ref email) = user.email {
            use rand::Rng;
            // Generate code before await to avoid Send issues
            let code = {
                let mut rng = rand::thread_rng();
                format!("{:06}", rng.gen_range(100000..999999))
            };
            
            // Store code in Redis with 10 minutes expiration
            state.services.redis.store_2fa_code(user.id, &code, 600).await?;
            
            // Send code via email
            state
                .services
                .email
                .send_2fa_code(email, &code, user.language)
                .await?;

            state.services.audit.log(
                audit::event::EMAIL_2FA_CODE_SENT,
                Some(user.id),
                Some("user"),
                Some(user.id),
                ip.clone(),
                Some(serde_json::json!({ "to": email.as_str() })),
            );
        }
    }

    let must_change_password = user.must_change_password;

    Ok(Json(LoginResponse {
        token,
        token_type: "Bearer".to_string(),
        expires_in: (state.config.users.jwt_expiration_hours * 3600) as i64,
        user: UserInfo {
            id: user.id,
            login: user.login.unwrap_or_default(),
            email: user.email,
            firstname: user.firstname,
            lastname: user.lastname,
            addr_street: user.addr_street,
            addr_zip_code: user.addr_zip_code,
            addr_city: user.addr_city,
            phone: user.phone,
            birthdate: user.birthdate,
            account_type: user.account_type.to_string(),
            language: user.language.unwrap_or(Language::French),
        },
        requires_2fa,
        two_factor_method,
        device_id,
        must_change_password,
    }))
}

/// Get current user profile
#[utoipa::path(
    get,
    path = "/auth/me",
    tag = "auth",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "Current user profile", body = UserInfo),
        (status = 401, description = "Not authenticated", body = ErrorResponse)
    )
)]
pub async fn me(
    State(state): State<crate::AppState>,
    AuthenticatedUser(claims): AuthenticatedUser,
) -> AppResult<Json<UserInfo>> {
    let user = state.services.users.get_by_id(claims.user_id).await?;

    Ok(Json(UserInfo {
        id: user.id,
        login: user.login.unwrap_or_default(),
        email: user.email,
        firstname: user.firstname,
        lastname: user.lastname,
        addr_street: user.addr_street,
        addr_zip_code: user.addr_zip_code,
        addr_city: user.addr_city,
        phone: user.phone,
        birthdate: user.birthdate,
        account_type: user.account_type.to_string(),
        language: user.language.unwrap_or(Language::French),
    }))
}

/// Verify 2FA code request
#[serde_as]
#[derive(Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct Verify2FARequest {
    /// User ID (from login response)
    #[serde_as(as = "DisplayFromStr")]
    #[schema(value_type = String)]
    pub user_id: i64,
    /// 2FA code (TOTP or email code)
    pub code: String,
    /// Device ID for trusted device feature (optional)
    pub device_id: Option<String>,
    /// Whether to trust this device for 90 days (optional, default: false)
    pub trust_device: Option<bool>,
}

/// Verify 2FA code response
#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct Verify2FAResponse {
    /// JWT access token
    pub token: String,
    /// Token type (always "Bearer")
    pub token_type: String,
    /// Token expiration time in seconds
    pub expires_in: i64,
}

/// Verify 2FA code endpoint
#[utoipa::path(
    post,
    path = "/auth/verify-2fa",
    tag = "auth",
    request_body = Verify2FARequest,
    responses(
        (status = 200, description = "2FA verification successful", body = Verify2FAResponse),
        (status = 401, description = "Invalid 2FA code", body = ErrorResponse)
    )
)]
pub async fn verify_2fa(
    State(state): State<crate::AppState>,
    ClientIp(ip): ClientIp,
    Json(request): Json<Verify2FARequest>,
) -> AppResult<Json<Verify2FAResponse>> {
    let trust_device = request.trust_device.unwrap_or(false);
    let verify_ctx = TwoFaVerifyAttemptAudit {
        trust_device,
        has_device_id: request.device_id.is_some(),
    };
    let result = state
        .services
        .users
        .verify_2fa(request.user_id, &request.code, request.device_id.as_deref(), trust_device)
        .await;

    match &result {
        Ok(_) => state.services.audit.log(
            audit::event::AUTH_2FA_VERIFIED,
            Some(request.user_id),
            Some("user"),
            Some(request.user_id),
            ip,
            Some(verify_ctx),
        ),
        Err(_) => state.services.audit.log(
            audit::event::AUTH_2FA_FAILED,
            Some(request.user_id),
            Some("user"),
            Some(request.user_id),
            ip,
            Some(verify_ctx),
        ),
    }

    let token = result?;
    Ok(Json(Verify2FAResponse {
        token,
        token_type: "Bearer".to_string(),
        expires_in: (state.config.users.jwt_expiration_hours * 3600) as i64,
    }))
}

/// Verify recovery code request
#[serde_as]
#[derive(Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct VerifyRecoveryRequest {
    /// User ID (from login response)
    #[serde_as(as = "DisplayFromStr")]
    #[schema(value_type = String)]
    pub user_id: i64,
    /// Recovery code
    pub code: String,
}

/// Password reset request
#[derive(Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct RequestPasswordResetRequest {
    /// Login or email address for the account.
    pub identifier: String,
    /// Full URL template for the reset link; must contain the literal `<token>` placeholder.
    /// If omitted, the server uses `[users].password_reset_url_template` from the app config.
    pub reset_url: Option<String>,
}

/// Response after a password-reset email was queued (public: no token in body).
#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct RequestPasswordResetResponse {
    pub message: String,
}

/// Response after password was reset with a valid token.
#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct ResetPasswordResponse {
    pub message: String,
}
#[derive(Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct ResetPasswordRequest {
    /// Reset token received by email
    pub token: String,
    /// New password
    pub new_password: String,
}

/// Verify recovery code endpoint
#[utoipa::path(
    post,
    path = "/auth/verify-recovery",
    tag = "auth",
    request_body = VerifyRecoveryRequest,
    responses(
        (status = 200, description = "Recovery code verification successful", body = Verify2FAResponse),
        (status = 401, description = "Invalid recovery code", body = ErrorResponse)
    )
)]
pub async fn verify_recovery(
    State(state): State<crate::AppState>,
    Json(request): Json<VerifyRecoveryRequest>,
) -> AppResult<Json<Verify2FAResponse>> {
    let token = state
        .services
        .users
        .verify_recovery_code(request.user_id, &request.code)
        .await?;

    Ok(Json(Verify2FAResponse {
        token,
        token_type: "Bearer".to_string(),
        expires_in: (state.config.users.jwt_expiration_hours * 3600) as i64,
    }))
}

/// Request password reset email
#[utoipa::path(
    post,
    path = "/auth/request-password-reset",
    tag = "auth",
    request_body = RequestPasswordResetRequest,
    responses(
        (status = 200, description = "Reset email sent", body = RequestPasswordResetResponse),
        (status = 400, description = "Invalid input (e.g. missing reset URL template, no email on account)", body = ErrorResponse),
        (status = 404, description = "No account for this login or email", body = ErrorResponse)
    )
)]
pub async fn request_password_reset(
    State(state): State<crate::AppState>,
    ClientIp(ip): ClientIp,
    Json(request): Json<RequestPasswordResetRequest>,
) -> AppResult<Json<RequestPasswordResetResponse>> {
    let url_template = request
        .reset_url
        .clone()
        .or_else(|| state.config.users.password_reset_url_template.clone())
        .ok_or_else(|| {
            crate::error::AppError::Validation(
                "reset_url is required, or configure users.password_reset_url_template on the server"
                    .to_string(),
            )
        })?;

    if !url_template.contains("<token>") {
        return Err(crate::error::AppError::Validation(
            "reset URL template must contain the <token> placeholder".to_string(),
        ));
    }

    let (email, token, lang, user_id) = state
        .services
        .users
        .request_password_reset(&request.identifier)
        .await?;

    let reset_url = url_template.replace("<token>", &token);

    state
        .services
        .email
        .send_password_reset(&email, &token, lang, Some(&reset_url))
        .await?;

    state.services.audit.log(
        audit::event::AUTH_PASSWORD_RESET_REQUESTED,
        Some(user_id),
        Some("user"),
        Some(user_id),
        ip.clone(),
        Some(serde_json::json!({ "identifier": request.identifier.as_str() })),
    );
    state.services.audit.log(
        audit::event::EMAIL_PASSWORD_RESET_SENT,
        Some(user_id),
        Some("user"),
        Some(user_id),
        ip,
        Some(serde_json::json!({ "to": email.as_str() })),
    );

    Ok(Json(RequestPasswordResetResponse {
        message: "Password reset email sent".to_string(),
    }))
}

/// Reset password with token
#[utoipa::path(
    post,
    path = "/auth/reset-password",
    tag = "auth",
    request_body = ResetPasswordRequest,
    responses(
        (status = 200, description = "Password reset successful", body = ResetPasswordResponse),
        (status = 400, description = "Invalid input", body = ErrorResponse),
        (status = 401, description = "Invalid or expired token", body = ErrorResponse)
    )
)]
pub async fn reset_password(
    State(state): State<crate::AppState>,
    ClientIp(ip): ClientIp,
    Json(request): Json<ResetPasswordRequest>,
) -> AppResult<Json<ResetPasswordResponse>> {

    if request.new_password.len() < 4 {
        return Err(crate::error::AppError::Validation(
            "Password must be at least 4 characters".to_string(),
        ));
    }

    state
        .services
        .users
        .reset_password(&request.token, &request.new_password)
        .await?;

    state.services.audit.log(
        audit::event::AUTH_PASSWORD_CHANGED,
        None,
        None,
        None,
        ip,
        Some(PasswordChangedViaResetAudit {
            source: "reset_token",
        }),
    );

    Ok(Json(ResetPasswordResponse {
        message: "Password has been reset".to_string(),
    }))
}

/// Setup 2FA request
#[derive(Deserialize, ToSchema)]
pub struct Setup2FARequest {
    /// 2FA method: "totp" or "email"
    pub method: String,
}

/// Setup 2FA response
#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct Setup2FAResponse {
    /// Provisioning URI for TOTP method (to generate QR code on client)
    pub provisioning_uri: Option<String>,
    /// Recovery codes (save these securely!)
    pub recovery_codes: Vec<String>,
}

/// Setup 2FA endpoint
#[utoipa::path(
    post,
    path = "/auth/setup-2fa",
    tag = "auth",
    security(("bearer_auth" = [])),
    request_body = Setup2FARequest,
    responses(
        (status = 200, description = "2FA setup successful", body = Setup2FAResponse),
        (status = 400, description = "Invalid request", body = ErrorResponse)
    )
)]
pub async fn setup_2fa(
    State(state): State<crate::AppState>,
    AuthenticatedUser(claims): AuthenticatedUser,
    ClientIp(ip): ClientIp,
    Json(request): Json<Setup2FARequest>,
) -> AppResult<Json<Setup2FAResponse>> {
    let user = state.services.users.get_by_id(claims.user_id).await?;

    let (totp_secret, provisioning_uri) = if request.method == "totp" {
        let (secret, uri) = state.services.users.setup_totp(&user)?;
        (Some(secret), Some(uri))
    } else {
        (None, None)
    };

    let recovery_codes = state
        .services
        .users
        .enable_2fa(claims.user_id, &request.method, totp_secret)
        .await?;

    state.services.audit.log(
        audit::event::AUTH_2FA_ENABLED,
        Some(claims.user_id),
        Some("user"),
        Some(claims.user_id),
        ip,
        Some(serde_json::json!({ "method": request.method.as_str() })),
    );

    Ok(Json(Setup2FAResponse { provisioning_uri, recovery_codes }))
}

/// Disable 2FA endpoint
#[utoipa::path(
    post,
    path = "/auth/disable-2fa",
    tag = "auth",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "2FA disabled successfully"),
        (status = 401, description = "Not authenticated", body = ErrorResponse)
    )
)]
pub async fn disable_2fa(
    State(state): State<crate::AppState>,
    AuthenticatedUser(claims): AuthenticatedUser,
    ClientIp(ip): ClientIp,
) -> AppResult<Json<serde_json::Value>> {
    state.services.users.disable_2fa(claims.user_id).await?;

    state.services.audit.log(
        audit::event::AUTH_2FA_DISABLED,
        Some(claims.user_id),
        Some("user"),
        Some(claims.user_id),
        ip,
        Some(UserIdAudit {
            user_id: claims.user_id,
        }),
    );

    Ok(Json(serde_json::json!({"message": "2FA disabled successfully"})))
}

/// First-login password change request
#[derive(Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct ChangePasswordRequest {
    /// New password (min 4 chars)
    pub new_password: String,
}

/// Change password using a scoped `change_password_only` token.
///
/// This endpoint is the **only** one that accepts the limited-scope JWT issued
/// when `must_change_password = true`. On success, the flag is cleared and a
/// full JWT valid for normal use is returned.
#[utoipa::path(
    post,
    path = "/auth/change-password",
    tag = "auth",
    security(("bearer_auth" = [])),
    request_body = ChangePasswordRequest,
    responses(
        (status = 200, description = "Password changed, full JWT returned", body = Verify2FAResponse),
        (status = 400, description = "Invalid password", body = ErrorResponse),
        (status = 403, description = "Requires a change-password scoped token", body = ErrorResponse)
    )
)]
pub async fn change_password(
    State(state): State<crate::AppState>,
    PasswordChangeUser(claims): PasswordChangeUser,
    ClientIp(ip): ClientIp,
    Json(request): Json<ChangePasswordRequest>,
) -> AppResult<Json<Verify2FAResponse>> {
    let token = state
        .services
        .users
        .change_password_first_login(claims.user_id, &request.new_password)
        .await?;

    state.services.audit.log(
        audit::event::AUTH_PASSWORD_CHANGED,
        Some(claims.user_id),
        Some("user"),
        Some(claims.user_id),
        ip,
        Some(PasswordChangedViaResetAudit {
            source: "first_login",
        }),
    );

    Ok(Json(Verify2FAResponse {
        token,
        token_type: "Bearer".to_string(),
        expires_in: (state.config.users.jwt_expiration_hours * 3600) as i64,
    }))
}

