//! Author model and related types

use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use utoipa::ToSchema;

/// Author function codes (matching original C implementation)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[repr(i32)]
pub enum AuthorFunction {
    Unknown = 0,
    Actor = 5,
    Adapter = 10,
    Annotator = 20,
    Arranger = 30,
    Artist = 40,
    Assignee = 50,
    AssociatedName = 60,
    Auctioneer = 65,
    Author = 70,
    AuthorQuote = 72,
    AuthorAfterwork = 75,
    AuthorIntroduction = 80,
    AuthorDialog = 90,
    Bibliographic = 100,
    Binder = 110,
    BindingDesigner = 120,
    BookDesigner = 130,
    BookjacketDesigner = 140,
    BookplateDesigner = 150,
    Bookseller = 160,
    Calligrapher = 170,
    Cartographer = 180,
    Censor = 190,
    Choreographer = 200,
    Collaborator = 205,
    Commentator = 210,
    CommentatorText = 212,
    Compiler = 220,
    Composer = 230,
    Compositor = 240,
    Conceptor = 245,
    Conductor = 250,
    CopyrightHolder = 260,
    Corrector = 270,
    Curator = 273,
    Dancer = 274,
    Dedicatee = 280,
    Dedicator = 290,
    Director = 300,
    Dissertant = 305,
    Distributor = 310,
    Donor = 320,
    DubiousAuthor = 330,
    Editor = 340,
    Engraver = 350,
    Etcher = 360,
    Expert = 365,
    FilmEditor = 370,
    Forger = 380,
    FormerOwner = 390,
    Funder = 400,
    GraphicTech = 410,
    Honoree = 420,
    Illuminator = 430,
    Illustrator = 440,
    Inscriber = 450,
    Interviewee = 460,
    Interviewer = 470,
    Librettist = 480,
    Licensee = 490,
    Licensor = 500,
    Lithographer = 510,
    Lyricist = 520,
    MetalEngraver = 530,
    Monitor = 540,
    Musician = 545,
    Narrator = 550,
    Originator = 560,
    Other = 570,
    Papermaker = 580,
    Performer = 590,
    Photographer = 600,
    Printer = 610,
    PrinterOfPlates = 620,
    Producer = 630,
    Programmer = 635,
    ProofReader = 640,
    Publisher = 650,
    PublishingDirector = 651,
    Addressee = 660,
    RecordingEngineer = 670,
    Reviewer = 675,
    Rubricator = 680,
    Scenarist = 690,
    ScientificAdvisor = 695,
    Scribe = 700,
    Sculptor = 705,
    Secretary = 710,
    Signer = 720,
    Singer = 721,
    Sponsor = 723,
    ThesisAdvisor = 727,
    Translator = 730,
    TypeDesigner = 740,
    Typographer = 750,
    WoodEngraver = 760,
    WriterOfMaterial = 770,
}

impl From<i32> for AuthorFunction {
    fn from(v: i32) -> Self {
        match v {
            5 => AuthorFunction::Actor,
            10 => AuthorFunction::Adapter,
            20 => AuthorFunction::Annotator,
            30 => AuthorFunction::Arranger,
            40 => AuthorFunction::Artist,
            50 => AuthorFunction::Assignee,
            60 => AuthorFunction::AssociatedName,
            65 => AuthorFunction::Auctioneer,
            70 => AuthorFunction::Author,
            72 => AuthorFunction::AuthorQuote,
            75 => AuthorFunction::AuthorAfterwork,
            80 => AuthorFunction::AuthorIntroduction,
            90 => AuthorFunction::AuthorDialog,
            100 => AuthorFunction::Bibliographic,
            110 => AuthorFunction::Binder,
            120 => AuthorFunction::BindingDesigner,
            130 => AuthorFunction::BookDesigner,
            140 => AuthorFunction::BookjacketDesigner,
            150 => AuthorFunction::BookplateDesigner,
            160 => AuthorFunction::Bookseller,
            170 => AuthorFunction::Calligrapher,
            180 => AuthorFunction::Cartographer,
            190 => AuthorFunction::Censor,
            200 => AuthorFunction::Choreographer,
            205 => AuthorFunction::Collaborator,
            210 => AuthorFunction::Commentator,
            212 => AuthorFunction::CommentatorText,
            220 => AuthorFunction::Compiler,
            230 => AuthorFunction::Composer,
            240 => AuthorFunction::Compositor,
            245 => AuthorFunction::Conceptor,
            250 => AuthorFunction::Conductor,
            260 => AuthorFunction::CopyrightHolder,
            270 => AuthorFunction::Corrector,
            273 => AuthorFunction::Curator,
            274 => AuthorFunction::Dancer,
            280 => AuthorFunction::Dedicatee,
            290 => AuthorFunction::Dedicator,
            300 => AuthorFunction::Director,
            305 => AuthorFunction::Dissertant,
            310 => AuthorFunction::Distributor,
            320 => AuthorFunction::Donor,
            330 => AuthorFunction::DubiousAuthor,
            340 => AuthorFunction::Editor,
            350 => AuthorFunction::Engraver,
            360 => AuthorFunction::Etcher,
            365 => AuthorFunction::Expert,
            370 => AuthorFunction::FilmEditor,
            380 => AuthorFunction::Forger,
            390 => AuthorFunction::FormerOwner,
            400 => AuthorFunction::Funder,
            410 => AuthorFunction::GraphicTech,
            420 => AuthorFunction::Honoree,
            430 => AuthorFunction::Illuminator,
            440 => AuthorFunction::Illustrator,
            450 => AuthorFunction::Inscriber,
            460 => AuthorFunction::Interviewee,
            470 => AuthorFunction::Interviewer,
            480 => AuthorFunction::Librettist,
            490 => AuthorFunction::Licensee,
            500 => AuthorFunction::Licensor,
            510 => AuthorFunction::Lithographer,
            520 => AuthorFunction::Lyricist,
            530 => AuthorFunction::MetalEngraver,
            540 => AuthorFunction::Monitor,
            545 => AuthorFunction::Musician,
            550 => AuthorFunction::Narrator,
            560 => AuthorFunction::Originator,
            570 => AuthorFunction::Other,
            580 => AuthorFunction::Papermaker,
            590 => AuthorFunction::Performer,
            600 => AuthorFunction::Photographer,
            610 => AuthorFunction::Printer,
            620 => AuthorFunction::PrinterOfPlates,
            630 => AuthorFunction::Producer,
            635 => AuthorFunction::Programmer,
            640 => AuthorFunction::ProofReader,
            650 => AuthorFunction::Publisher,
            651 => AuthorFunction::PublishingDirector,
            660 => AuthorFunction::Addressee,
            670 => AuthorFunction::RecordingEngineer,
            675 => AuthorFunction::Reviewer,
            680 => AuthorFunction::Rubricator,
            690 => AuthorFunction::Scenarist,
            695 => AuthorFunction::ScientificAdvisor,
            700 => AuthorFunction::Scribe,
            705 => AuthorFunction::Sculptor,
            710 => AuthorFunction::Secretary,
            720 => AuthorFunction::Signer,
            721 => AuthorFunction::Singer,
            723 => AuthorFunction::Sponsor,
            727 => AuthorFunction::ThesisAdvisor,
            730 => AuthorFunction::Translator,
            740 => AuthorFunction::TypeDesigner,
            750 => AuthorFunction::Typographer,
            760 => AuthorFunction::WoodEngraver,
            770 => AuthorFunction::WriterOfMaterial,
            _ => AuthorFunction::Unknown,
        }
    }
}

/// Full author model from database
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Author {
    pub id: i32,
    pub key: Option<String>,
    pub lastname: Option<String>,
    pub firstname: Option<String>,
    pub bio: Option<String>,
    pub notes: Option<String>,
}

/// Author with function for item relationships
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct AuthorWithFunction {
    pub id: i32,
    pub lastname: Option<String>,
    pub firstname: Option<String>,
    pub bio: Option<String>,
    pub notes: Option<String>,
    pub function: Option<String>,
}

/// Create author request
#[derive(Debug, Deserialize)]
pub struct CreateAuthor {
    pub lastname: String,
    pub firstname: Option<String>,
    pub bio: Option<String>,
    pub notes: Option<String>,
}

/// Update author request
#[derive(Debug, Deserialize)]
pub struct UpdateAuthor {
    pub lastname: Option<String>,
    pub firstname: Option<String>,
    pub bio: Option<String>,
    pub notes: Option<String>,
}

